import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 799000,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
      sold: 95,
      sale: 10,
      discount: 10,
      countInStock: 50,
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 899000,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner2.jpg',
      sold: 85,
      sale: 25,
      discount: 20,
      countInStock: 55,
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 999000,
      brand: 'Raymond',
      rating: 4.6,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
      sold: 75,
      sale: 33,
      discount: 15,
      countInStock: 60,
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 1999000,
      brand: 'Oliver',
      rating: 4.7,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pants',
      sold: 65,
      sale: 49,
      discount: 35,
      countInStock: 65,
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 1299000,
      brand: 'Zara',
      rating: 4.8,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular pants',
      sold: 55,
      sale: 15,
      discount: 50,
      countInStock: 0,
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 599000,
      brand: 'Casely',
      rating: 4.8,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
      sold: 45,
      sale: 65,
      discount: 66,
      countInStock: 0,
    },
    {
      name: 'Áo khoác Jean',
      slug: 'ao-khoac-jean',
      category: 'Jean',
      image: '/images/1.webp',
      price: 499000,
      brand: 'Gucci',
      rating: 4.7,
      numReviews: 12,
      countInStock: 20,
      description: 'A popular jean',
      sold: 35,
      sale: 38,
      discount: 99,
      countInStock: 50,
    },
  ],
};

export default data;
